from django.utils.translation import ugettext_lazy as _

# Nicely titled (and translatable) country names.
COUNTRIES = (
    ('AF', _(u'Afghanistan')),
    ('AX', _(u'\xc5land Islands')),
    ('AL', _(u'Albania')),
    ('DZ', _(u'Algeria')),
    ('AS', _(u'American Samoa')),
    ('AD', _(u'Andorra')),
    ('AO', _(u'Angola')),
    ('AI', _(u'Anguilla')),
    ('AQ', _(u'Antarctica')),
    ('AG', _(u'Antigua and Barbuda')),
    ('AR', _(u'Argentina')),
    ('AM', _(u'Armenia')),
    ('AW', _(u'Aruba')),
    ('AU', _(u'Australia')),
    ('AT', _(u'Austria')),
    ('AZ', _(u'Azerbaijan')),
    ('BS', _(u'Bahamas')),
    ('BH', _(u'Bahrain')),
    ('BD', _(u'Bangladesh')),
    ('BB', _(u'Barbados')),
    ('BY', _(u'Belarus')),
    ('BE', _(u'Belgium')),
    ('BZ', _(u'Belize')),
    ('BJ', _(u'Benin')),
    ('BM', _(u'Bermuda')),
    ('BT', _(u'Bhutan')),
    ('BO', _(u'Bolivia, Plurinational State of')),
    ('BQ', _(u'Bonaire, Sint Eustatius and Saba')),
    ('BA', _(u'Bosnia and Herzegovina')),
    ('BW', _(u'Botswana')),
    ('BV', _(u'Bouvet Island')),
    ('BR', _(u'Brazil')),
    ('IO', _(u'British Indian Ocean Territory')),
    ('BN', _(u'Brunei Darussalam')),
    ('BG', _(u'Bulgaria')),
    ('BF', _(u'Burkina Faso')),
    ('BI', _(u'Burundi')),
    ('KH', _(u'Cambodia')),
    ('CM', _(u'Cameroon')),
    ('CA', _(u'Canada')),
    ('CV', _(u'Cape Verde')),
    ('KY', _(u'Cayman Islands')),
    ('CF', _(u'Central African Republic')),
    ('TD', _(u'Chad')),
    ('CL', _(u'Chile')),
    ('CN', _(u'China')),
    ('CX', _(u'Christmas Island')),
    ('CC', _(u'Cocos (Keeling) Islands')),
    ('CO', _(u'Colombia')),
    ('KM', _(u'Comoros')),
    ('CG', _(u'Congo')),
    ('CD', _(u'Congo, The Democratic Republic of the')),
    ('CK', _(u'Cook Islands')),
    ('CR', _(u'Costa Rica')),
    ('CI', _(u"C\xf4te D'ivoire")),
    ('HR', _(u'Croatia')),
    ('CU', _(u'Cuba')),
    ('CW', _(u'Cura\xe7ao')),
    ('CY', _(u'Cyprus')),
    ('CZ', _(u'Czech Republic')),
    ('DK', _(u'Denmark')),
    ('DJ', _(u'Djibouti')),
    ('DM', _(u'Dominica')),
    ('DO', _(u'Dominican Republic')),
    ('EC', _(u'Ecuador')),
    ('EG', _(u'Egypt')),
    ('SV', _(u'El Salvador')),
    ('GQ', _(u'Equatorial Guinea')),
    ('ER', _(u'Eritrea')),
    ('EE', _(u'Estonia')),
    ('ET', _(u'Ethiopia')),
    ('FK', _(u'Falkland Islands (Malvinas)')),
    ('FO', _(u'Faroe Islands')),
    ('FJ', _(u'Fiji')),
    ('FI', _(u'Finland')),
    ('FR', _(u'France')),
    ('GF', _(u'French Guiana')),
    ('PF', _(u'French Polynesia')),
    ('TF', _(u'French Southern Territories')),
    ('GA', _(u'Gabon')),
    ('GM', _(u'Gambia')),
    ('GE', _(u'Georgia')),
    ('DE', _(u'Germany')),
    ('GH', _(u'Ghana')),
    ('GI', _(u'Gibraltar')),
    ('GR', _(u'Greece')),
    ('GL', _(u'Greenland')),
    ('GD', _(u'Grenada')),
    ('GP', _(u'Guadeloupe')),
    ('GU', _(u'Guam')),
    ('GT', _(u'Guatemala')),
    ('GG', _(u'Guernsey')),
    ('GN', _(u'Guinea')),
    ('GW', _(u'Guinea-bissau')),
    ('GY', _(u'Guyana')),
    ('HT', _(u'Haiti')),
    ('HM', _(u'Heard Island and McDonald Islands')),
    ('VA', _(u'Holy See (Vatican City State)')),
    ('HN', _(u'Honduras')),
    ('HK', _(u'Hong Kong')),
    ('HU', _(u'Hungary')),
    ('IS', _(u'Iceland')),
    ('IN', _(u'India')),
    ('ID', _(u'Indonesia')),
    ('IR', _(u'Iran, Islamic Republic of')),
    ('IQ', _(u'Iraq')),
    ('IE', _(u'Ireland')),
    ('IM', _(u'Isle of Man')),
    ('IL', _(u'Israel')),
    ('IT', _(u'Italy')),
    ('JM', _(u'Jamaica')),
    ('JP', _(u'Japan')),
    ('JE', _(u'Jersey')),
    ('JO', _(u'Jordan')),
    ('KZ', _(u'Kazakhstan')),
    ('KE', _(u'Kenya')),
    ('KI', _(u'Kiribati')),
    ('KP', _(u"Korea, Democratic People's Republic of")),
    ('KR', _(u'Korea, Republic of')),
    ('KW', _(u'Kuwait')),
    ('KG', _(u'Kyrgyzstan')),
    ('LA', _(u"Lao People's Democratic Republic")),
    ('LV', _(u'Latvia')),
    ('LB', _(u'Lebanon')),
    ('LS', _(u'Lesotho')),
    ('LR', _(u'Liberia')),
    ('LY', _(u'Libya')),
    ('LI', _(u'Liechtenstein')),
    ('LT', _(u'Lithuania')),
    ('LU', _(u'Luxembourg')),
    ('MO', _(u'Macao')),
    ('MK', _(u'Macedonia, The Former Yugoslav Republic of')),
    ('MG', _(u'Madagascar')),
    ('MW', _(u'Malawi')),
    ('MY', _(u'Malaysia')),
    ('MV', _(u'Maldives')),
    ('ML', _(u'Mali')),
    ('MT', _(u'Malta')),
    ('MH', _(u'Marshall Islands')),
    ('MQ', _(u'Martinique')),
    ('MR', _(u'Mauritania')),
    ('MU', _(u'Mauritius')),
    ('YT', _(u'Mayotte')),
    ('MX', _(u'Mexico')),
    ('FM', _(u'Micronesia, Federated States of')),
    ('MD', _(u'Moldova, Republic of')),
    ('MC', _(u'Monaco')),
    ('MN', _(u'Mongolia')),
    ('ME', _(u'Montenegro')),
    ('MS', _(u'Montserrat')),
    ('MA', _(u'Morocco')),
    ('MZ', _(u'Mozambique')),
    ('MM', _(u'Myanmar')),
    ('NA', _(u'Namibia')),
    ('NR', _(u'Nauru')),
    ('NP', _(u'Nepal')),
    ('NL', _(u'Netherlands')),
    ('NC', _(u'New Caledonia')),
    ('NZ', _(u'New Zealand')),
    ('NI', _(u'Nicaragua')),
    ('NE', _(u'Niger')),
    ('NG', _(u'Nigeria')),
    ('NU', _(u'Niue')),
    ('NF', _(u'Norfolk Island')),
    ('MP', _(u'Northern Mariana Islands')),
    ('NO', _(u'Norway')),
    ('OM', _(u'Oman')),
    ('PK', _(u'Pakistan')),
    ('PW', _(u'Palau')),
    ('PS', _(u'Palestinian Territory, Occupied')),
    ('PA', _(u'Panama')),
    ('PG', _(u'Papua New Guinea')),
    ('PY', _(u'Paraguay')),
    ('PE', _(u'Peru')),
    ('PH', _(u'Philippines')),
    ('PN', _(u'Pitcairn')),
    ('PL', _(u'Poland')),
    ('PT', _(u'Portugal')),
    ('PR', _(u'Puerto Rico')),
    ('QA', _(u'Qatar')),
    ('RE', _(u'R\xe9union')),
    ('RO', _(u'Romania')),
    ('RU', _(u'Russian Federation')),
    ('RW', _(u'Rwanda')),
    ('BL', _(u'Saint Barth\xe9lemy')),
    ('SH', _(u'Saint Helena, Ascension and Tristan Da Cunha')),
    ('KN', _(u'Saint Kitts and Nevis')),
    ('LC', _(u'Saint Lucia')),
    ('MF', _(u'Saint Martin (French Part)')),
    ('PM', _(u'Saint Pierre and Miquelon')),
    ('VC', _(u'Saint Vincent and the Grenadines')),
    ('WS', _(u'Samoa')),
    ('SM', _(u'San Marino')),
    ('ST', _(u'Sao Tome and Principe')),
    ('SA', _(u'Saudi Arabia')),
    ('SN', _(u'Senegal')),
    ('RS', _(u'Serbia')),
    ('SC', _(u'Seychelles')),
    ('SL', _(u'Sierra Leone')),
    ('SG', _(u'Singapore')),
    ('SX', _(u'Sint Maarten (Dutch Part)')),
    ('SK', _(u'Slovakia')),
    ('SI', _(u'Slovenia')),
    ('SB', _(u'Solomon Islands')),
    ('SO', _(u'Somalia')),
    ('ZA', _(u'South Africa')),
    ('GS', _(u'South Georgia and the South Sandwich Islands')),
    ('SS', _(u'South Sudan')),
    ('ES', _(u'Spain')),
    ('LK', _(u'Sri Lanka')),
    ('SD', _(u'Sudan')),
    ('SR', _(u'Suriname')),
    ('SJ', _(u'Svalbard and Jan Mayen')),
    ('SZ', _(u'Swaziland')),
    ('SE', _(u'Sweden')),
    ('CH', _(u'Switzerland')),
    ('SY', _(u'Syrian Arab Republic')),
    ('TW', _(u'Taiwan, Province of China')),
    ('TJ', _(u'Tajikistan')),
    ('TZ', _(u'Tanzania, United Republic of')),
    ('TH', _(u'Thailand')),
    ('TL', _(u'Timor-leste')),
    ('TG', _(u'Togo')),
    ('TK', _(u'Tokelau')),
    ('TO', _(u'Tonga')),
    ('TT', _(u'Trinidad and Tobago')),
    ('TN', _(u'Tunisia')),
    ('TR', _(u'Turkey')),
    ('TM', _(u'Turkmenistan')),
    ('TC', _(u'Turks and Caicos Islands')),
    ('TV', _(u'Tuvalu')),
    ('UG', _(u'Uganda')),
    ('UA', _(u'Ukraine')),
    ('AE', _(u'United Arab Emirates')),
    ('GB', _(u'United Kingdom')),
    ('US', _(u'United States')),
    ('UM', _(u'United States Minor Outlying Islands')),
    ('UY', _(u'Uruguay')),
    ('UZ', _(u'Uzbekistan')),
    ('VU', _(u'Vanuatu')),
    ('VE', _(u'Venezuela, Bolivarian Republic of')),
    ('VN', _(u'Viet Nam')),
    ('VG', _(u'Virgin Islands, British')),
    ('VI', _(u'Virgin Islands, U.S.')),
    ('WF', _(u'Wallis and Futuna')),
    ('EH', _(u'Western Sahara')),
    ('YE', _(u'Yemen')),
    ('ZM', _(u'Zambia')),
    ('ZW', _(u'Zimbabwe')),
)

# Nicely titled country names with duplicates for those which contain a comma
# (containing the non-comma'd version).
COUNTRIES_PLUS = (
    ('AF', _(u'Afghanistan')),
    ('AX', _(u'\xc5land Islands')),
    ('AL', _(u'Albania')),
    ('DZ', _(u'Algeria')),
    ('AS', _(u'American Samoa')),
    ('AD', _(u'Andorra')),
    ('AO', _(u'Angola')),
    ('AI', _(u'Anguilla')),
    ('AQ', _(u'Antarctica')),
    ('AG', _(u'Antigua and Barbuda')),
    ('AR', _(u'Argentina')),
    ('AM', _(u'Armenia')),
    ('AW', _(u'Aruba')),
    ('SH', _(u'Ascension and Tristan Da Cunha Saint Helena')),
    ('AU', _(u'Australia')),
    ('AT', _(u'Austria')),
    ('AZ', _(u'Azerbaijan')),
    ('BS', _(u'Bahamas')),
    ('BH', _(u'Bahrain')),
    ('BD', _(u'Bangladesh')),
    ('BB', _(u'Barbados')),
    ('BY', _(u'Belarus')),
    ('BE', _(u'Belgium')),
    ('BZ', _(u'Belize')),
    ('BJ', _(u'Benin')),
    ('BM', _(u'Bermuda')),
    ('BT', _(u'Bhutan')),
    ('VE', _(u'Bolivarian Republic of Venezuela')),
    ('BO', _(u'Bolivia, Plurinational State of')),
    ('BQ', _(u'Bonaire, Sint Eustatius and Saba')),
    ('BA', _(u'Bosnia and Herzegovina')),
    ('BW', _(u'Botswana')),
    ('BV', _(u'Bouvet Island')),
    ('BR', _(u'Brazil')),
    ('IO', _(u'British Indian Ocean Territory')),
    ('VG', _(u'British Virgin Islands')),
    ('BN', _(u'Brunei Darussalam')),
    ('BG', _(u'Bulgaria')),
    ('BF', _(u'Burkina Faso')),
    ('BI', _(u'Burundi')),
    ('KH', _(u'Cambodia')),
    ('CM', _(u'Cameroon')),
    ('CA', _(u'Canada')),
    ('CV', _(u'Cape Verde')),
    ('KY', _(u'Cayman Islands')),
    ('CF', _(u'Central African Republic')),
    ('TD', _(u'Chad')),
    ('CL', _(u'Chile')),
    ('CN', _(u'China')),
    ('CX', _(u'Christmas Island')),
    ('CC', _(u'Cocos (Keeling) Islands')),
    ('CO', _(u'Colombia')),
    ('KM', _(u'Comoros')),
    ('CG', _(u'Congo')),
    ('CD', _(u'Congo, The Democratic Republic of the')),
    ('CK', _(u'Cook Islands')),
    ('CR', _(u'Costa Rica')),
    ('CI', _(u"C\xf4te D'ivoire")),
    ('HR', _(u'Croatia')),
    ('CU', _(u'Cuba')),
    ('CW', _(u'Cura\xe7ao')),
    ('CY', _(u'Cyprus')),
    ('CZ', _(u'Czech Republic')),
    ('KP', _(u"Democratic People's Republic of Korea")),
    ('DK', _(u'Denmark')),
    ('DJ', _(u'Djibouti')),
    ('DM', _(u'Dominica')),
    ('DO', _(u'Dominican Republic')),
    ('EC', _(u'Ecuador')),
    ('EG', _(u'Egypt')),
    ('SV', _(u'El Salvador')),
    ('GQ', _(u'Equatorial Guinea')),
    ('ER', _(u'Eritrea')),
    ('EE', _(u'Estonia')),
    ('ET', _(u'Ethiopia')),
    ('FK', _(u'Falkland Islands (Malvinas)')),
    ('FO', _(u'Faroe Islands')),
    ('FM', _(u'Federated States of Micronesia')),
    ('FJ', _(u'Fiji')),
    ('FI', _(u'Finland')),
    ('FR', _(u'France')),
    ('GF', _(u'French Guiana')),
    ('PF', _(u'French Polynesia')),
    ('TF', _(u'French Southern Territories')),
    ('GA', _(u'Gabon')),
    ('GM', _(u'Gambia')),
    ('GE', _(u'Georgia')),
    ('DE', _(u'Germany')),
    ('GH', _(u'Ghana')),
    ('GI', _(u'Gibraltar')),
    ('GR', _(u'Greece')),
    ('GL', _(u'Greenland')),
    ('GD', _(u'Grenada')),
    ('GP', _(u'Guadeloupe')),
    ('GU', _(u'Guam')),
    ('GT', _(u'Guatemala')),
    ('GG', _(u'Guernsey')),
    ('GN', _(u'Guinea')),
    ('GW', _(u'Guinea-bissau')),
    ('GY', _(u'Guyana')),
    ('HT', _(u'Haiti')),
    ('HM', _(u'Heard Island and McDonald Islands')),
    ('VA', _(u'Holy See (Vatican City State)')),
    ('HN', _(u'Honduras')),
    ('HK', _(u'Hong Kong')),
    ('HU', _(u'Hungary')),
    ('IS', _(u'Iceland')),
    ('IN', _(u'India')),
    ('ID', _(u'Indonesia')),
    ('IR', _(u'Iran, Islamic Republic of')),
    ('IQ', _(u'Iraq')),
    ('IE', _(u'Ireland')),
    ('IR', _(u'Islamic Republic of Iran')),
    ('IM', _(u'Isle of Man')),
    ('IL', _(u'Israel')),
    ('IT', _(u'Italy')),
    ('JM', _(u'Jamaica')),
    ('JP', _(u'Japan')),
    ('JE', _(u'Jersey')),
    ('JO', _(u'Jordan')),
    ('KZ', _(u'Kazakhstan')),
    ('KE', _(u'Kenya')),
    ('KI', _(u'Kiribati')),
    ('KP', _(u"Korea, Democratic People's Republic of")),
    ('KR', _(u'Korea, Republic of')),
    ('KW', _(u'Kuwait')),
    ('KG', _(u'Kyrgyzstan')),
    ('LA', _(u"Lao People's Democratic Republic")),
    ('LV', _(u'Latvia')),
    ('LB', _(u'Lebanon')),
    ('LS', _(u'Lesotho')),
    ('LR', _(u'Liberia')),
    ('LY', _(u'Libya')),
    ('LI', _(u'Liechtenstein')),
    ('LT', _(u'Lithuania')),
    ('LU', _(u'Luxembourg')),
    ('MO', _(u'Macao')),
    ('MK', _(u'Macedonia, The Former Yugoslav Republic of')),
    ('MG', _(u'Madagascar')),
    ('MW', _(u'Malawi')),
    ('MY', _(u'Malaysia')),
    ('MV', _(u'Maldives')),
    ('ML', _(u'Mali')),
    ('MT', _(u'Malta')),
    ('MH', _(u'Marshall Islands')),
    ('MQ', _(u'Martinique')),
    ('MR', _(u'Mauritania')),
    ('MU', _(u'Mauritius')),
    ('YT', _(u'Mayotte')),
    ('MX', _(u'Mexico')),
    ('FM', _(u'Micronesia, Federated States of')),
    ('MD', _(u'Moldova, Republic of')),
    ('MC', _(u'Monaco')),
    ('MN', _(u'Mongolia')),
    ('ME', _(u'Montenegro')),
    ('MS', _(u'Montserrat')),
    ('MA', _(u'Morocco')),
    ('MZ', _(u'Mozambique')),
    ('MM', _(u'Myanmar')),
    ('NA', _(u'Namibia')),
    ('NR', _(u'Nauru')),
    ('NP', _(u'Nepal')),
    ('NL', _(u'Netherlands')),
    ('NC', _(u'New Caledonia')),
    ('NZ', _(u'New Zealand')),
    ('NI', _(u'Nicaragua')),
    ('NE', _(u'Niger')),
    ('NG', _(u'Nigeria')),
    ('NU', _(u'Niue')),
    ('NF', _(u'Norfolk Island')),
    ('MP', _(u'Northern Mariana Islands')),
    ('NO', _(u'Norway')),
    ('PS', _(u'Occupied Palestinian Territory')),
    ('OM', _(u'Oman')),
    ('PK', _(u'Pakistan')),
    ('PW', _(u'Palau')),
    ('PS', _(u'Palestinian Territory, Occupied')),
    ('PA', _(u'Panama')),
    ('PG', _(u'Papua New Guinea')),
    ('PY', _(u'Paraguay')),
    ('PE', _(u'Peru')),
    ('PH', _(u'Philippines')),
    ('PN', _(u'Pitcairn')),
    ('BO', _(u'Plurinational State of Bolivia')),
    ('PL', _(u'Poland')),
    ('PT', _(u'Portugal')),
    ('TW', _(u'Province of China Taiwan')),
    ('PR', _(u'Puerto Rico')),
    ('QA', _(u'Qatar')),
    ('KR', _(u'Republic of Korea')),
    ('MD', _(u'Republic of Moldova')),
    ('RE', _(u'R\xe9union')),
    ('RO', _(u'Romania')),
    ('RU', _(u'Russian Federation')),
    ('RW', _(u'Rwanda')),
    ('BL', _(u'Saint Barth\xe9lemy')),
    ('SH', _(u'Saint Helena, Ascension and Tristan Da Cunha')),
    ('KN', _(u'Saint Kitts and Nevis')),
    ('LC', _(u'Saint Lucia')),
    ('MF', _(u'Saint Martin (French Part)')),
    ('PM', _(u'Saint Pierre and Miquelon')),
    ('VC', _(u'Saint Vincent and the Grenadines')),
    ('WS', _(u'Samoa')),
    ('SM', _(u'San Marino')),
    ('ST', _(u'Sao Tome and Principe')),
    ('SA', _(u'Saudi Arabia')),
    ('SN', _(u'Senegal')),
    ('RS', _(u'Serbia')),
    ('SC', _(u'Seychelles')),
    ('SL', _(u'Sierra Leone')),
    ('SG', _(u'Singapore')),
    ('BQ', _(u'Sint Eustatius and Saba Bonaire')),
    ('SX', _(u'Sint Maarten (Dutch Part)')),
    ('SK', _(u'Slovakia')),
    ('SI', _(u'Slovenia')),
    ('SB', _(u'Solomon Islands')),
    ('SO', _(u'Somalia')),
    ('ZA', _(u'South Africa')),
    ('GS', _(u'South Georgia and the South Sandwich Islands')),
    ('SS', _(u'South Sudan')),
    ('ES', _(u'Spain')),
    ('LK', _(u'Sri Lanka')),
    ('SD', _(u'Sudan')),
    ('SR', _(u'Suriname')),
    ('SJ', _(u'Svalbard and Jan Mayen')),
    ('SZ', _(u'Swaziland')),
    ('SE', _(u'Sweden')),
    ('CH', _(u'Switzerland')),
    ('SY', _(u'Syrian Arab Republic')),
    ('TW', _(u'Taiwan, Province of China')),
    ('TJ', _(u'Tajikistan')),
    ('TZ', _(u'Tanzania, United Republic of')),
    ('TH', _(u'Thailand')),
    ('CD', _(u'The Democratic Republic of the Congo')),
    ('MK', _(u'The Former Yugoslav Republic of Macedonia')),
    ('TL', _(u'Timor-leste')),
    ('TG', _(u'Togo')),
    ('TK', _(u'Tokelau')),
    ('TO', _(u'Tonga')),
    ('TT', _(u'Trinidad and Tobago')),
    ('TN', _(u'Tunisia')),
    ('TR', _(u'Turkey')),
    ('TM', _(u'Turkmenistan')),
    ('TC', _(u'Turks and Caicos Islands')),
    ('TV', _(u'Tuvalu')),
    ('VI', _(u'U.S. Virgin Islands')),
    ('UG', _(u'Uganda')),
    ('UA', _(u'Ukraine')),
    ('AE', _(u'United Arab Emirates')),
    ('GB', _(u'United Kingdom')),
    ('TZ', _(u'United Republic of Tanzania')),
    ('US', _(u'United States')),
    ('UM', _(u'United States Minor Outlying Islands')),
    ('UY', _(u'Uruguay')),
    ('UZ', _(u'Uzbekistan')),
    ('VU', _(u'Vanuatu')),
    ('VE', _(u'Venezuela, Bolivarian Republic of')),
    ('VN', _(u'Viet Nam')),
    ('VG', _(u'Virgin Islands, British')),
    ('VI', _(u'Virgin Islands, U.S.')),
    ('WF', _(u'Wallis and Futuna')),
    ('EH', _(u'Western Sahara')),
    ('YE', _(u'Yemen')),
    ('ZM', _(u'Zambia')),
    ('ZW', _(u'Zimbabwe')),
)

# Official capitalized country names.
OFFICIAL_COUNTRIES = {
    'AF': u'AFGHANISTAN',
    'AX': u'\xc5LAND ISLANDS',
    'AL': u'ALBANIA',
    'DZ': u'ALGERIA',
    'AS': u'AMERICAN SAMOA',
    'AD': u'ANDORRA',
    'AO': u'ANGOLA',
    'AI': u'ANGUILLA',
    'AQ': u'ANTARCTICA',
    'AG': u'ANTIGUA AND BARBUDA',
    'AR': u'ARGENTINA',
    'AM': u'ARMENIA',
    'AW': u'ARUBA',
    'AU': u'AUSTRALIA',
    'AT': u'AUSTRIA',
    'AZ': u'AZERBAIJAN',
    'BS': u'BAHAMAS',
    'BH': u'BAHRAIN',
    'BD': u'BANGLADESH',
    'BB': u'BARBADOS',
    'BY': u'BELARUS',
    'BE': u'BELGIUM',
    'BZ': u'BELIZE',
    'BJ': u'BENIN',
    'BM': u'BERMUDA',
    'BT': u'BHUTAN',
    'BO': u'BOLIVIA, PLURINATIONAL STATE OF',
    'BQ': u'BONAIRE, SINT EUSTATIUS AND SABA',
    'BA': u'BOSNIA AND HERZEGOVINA',
    'BW': u'BOTSWANA',
    'BV': u'BOUVET ISLAND',
    'BR': u'BRAZIL',
    'IO': u'BRITISH INDIAN OCEAN TERRITORY',
    'BN': u'BRUNEI DARUSSALAM',
    'BG': u'BULGARIA',
    'BF': u'BURKINA FASO',
    'BI': u'BURUNDI',
    'KH': u'CAMBODIA',
    'CM': u'CAMEROON',
    'CA': u'CANADA',
    'CV': u'CAPE VERDE',
    'KY': u'CAYMAN ISLANDS',
    'CF': u'CENTRAL AFRICAN REPUBLIC',
    'TD': u'CHAD',
    'CL': u'CHILE',
    'CN': u'CHINA',
    'CX': u'CHRISTMAS ISLAND',
    'CC': u'COCOS (KEELING) ISLANDS',
    'CO': u'COLOMBIA',
    'KM': u'COMOROS',
    'CG': u'CONGO',
    'CD': u'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
    'CK': u'COOK ISLANDS',
    'CR': u'COSTA RICA',
    'CI': u"C\xd4TE D'IVOIRE",
    'HR': u'CROATIA',
    'CU': u'CUBA',
    'CW': u'CURA\xc7AO',
    'CY': u'CYPRUS',
    'CZ': u'CZECH REPUBLIC',
    'DK': u'DENMARK',
    'DJ': u'DJIBOUTI',
    'DM': u'DOMINICA',
    'DO': u'DOMINICAN REPUBLIC',
    'EC': u'ECUADOR',
    'EG': u'EGYPT',
    'SV': u'EL SALVADOR',
    'GQ': u'EQUATORIAL GUINEA',
    'ER': u'ERITREA',
    'EE': u'ESTONIA',
    'ET': u'ETHIOPIA',
    'FK': u'FALKLAND ISLANDS (MALVINAS)',
    'FO': u'FAROE ISLANDS',
    'FJ': u'FIJI',
    'FI': u'FINLAND',
    'FR': u'FRANCE',
    'GF': u'FRENCH GUIANA',
    'PF': u'FRENCH POLYNESIA',
    'TF': u'FRENCH SOUTHERN TERRITORIES',
    'GA': u'GABON',
    'GM': u'GAMBIA',
    'GE': u'GEORGIA',
    'DE': u'GERMANY',
    'GH': u'GHANA',
    'GI': u'GIBRALTAR',
    'GR': u'GREECE',
    'GL': u'GREENLAND',
    'GD': u'GRENADA',
    'GP': u'GUADELOUPE',
    'GU': u'GUAM',
    'GT': u'GUATEMALA',
    'GG': u'GUERNSEY',
    'GN': u'GUINEA',
    'GW': u'GUINEA-BISSAU',
    'GY': u'GUYANA',
    'HT': u'HAITI',
    'HM': u'HEARD ISLAND AND MCDONALD ISLANDS',
    'VA': u'HOLY SEE (VATICAN CITY STATE)',
    'HN': u'HONDURAS',
    'HK': u'HONG KONG',
    'HU': u'HUNGARY',
    'IS': u'ICELAND',
    'IN': u'INDIA',
    'ID': u'INDONESIA',
    'IR': u'IRAN, ISLAMIC REPUBLIC OF',
    'IQ': u'IRAQ',
    'IE': u'IRELAND',
    'IM': u'ISLE OF MAN',
    'IL': u'ISRAEL',
    'IT': u'ITALY',
    'JM': u'JAMAICA',
    'JP': u'JAPAN',
    'JE': u'JERSEY',
    'JO': u'JORDAN',
    'KZ': u'KAZAKHSTAN',
    'KE': u'KENYA',
    'KI': u'KIRIBATI',
    'KP': u"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    'KR': u'KOREA, REPUBLIC OF',
    'KW': u'KUWAIT',
    'KG': u'KYRGYZSTAN',
    'LA': u"LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    'LV': u'LATVIA',
    'LB': u'LEBANON',
    'LS': u'LESOTHO',
    'LR': u'LIBERIA',
    'LY': u'LIBYA',
    'LI': u'LIECHTENSTEIN',
    'LT': u'LITHUANIA',
    'LU': u'LUXEMBOURG',
    'MO': u'MACAO',
    'MK': u'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
    'MG': u'MADAGASCAR',
    'MW': u'MALAWI',
    'MY': u'MALAYSIA',
    'MV': u'MALDIVES',
    'ML': u'MALI',
    'MT': u'MALTA',
    'MH': u'MARSHALL ISLANDS',
    'MQ': u'MARTINIQUE',
    'MR': u'MAURITANIA',
    'MU': u'MAURITIUS',
    'YT': u'MAYOTTE',
    'MX': u'MEXICO',
    'FM': u'MICRONESIA, FEDERATED STATES OF',
    'MD': u'MOLDOVA, REPUBLIC OF',
    'MC': u'MONACO',
    'MN': u'MONGOLIA',
    'ME': u'MONTENEGRO',
    'MS': u'MONTSERRAT',
    'MA': u'MOROCCO',
    'MZ': u'MOZAMBIQUE',
    'MM': u'MYANMAR',
    'NA': u'NAMIBIA',
    'NR': u'NAURU',
    'NP': u'NEPAL',
    'NL': u'NETHERLANDS',
    'NC': u'NEW CALEDONIA',
    'NZ': u'NEW ZEALAND',
    'NI': u'NICARAGUA',
    'NE': u'NIGER',
    'NG': u'NIGERIA',
    'NU': u'NIUE',
    'NF': u'NORFOLK ISLAND',
    'MP': u'NORTHERN MARIANA ISLANDS',
    'NO': u'NORWAY',
    'OM': u'OMAN',
    'PK': u'PAKISTAN',
    'PW': u'PALAU',
    'PS': u'PALESTINIAN TERRITORY, OCCUPIED',
    'PA': u'PANAMA',
    'PG': u'PAPUA NEW GUINEA',
    'PY': u'PARAGUAY',
    'PE': u'PERU',
    'PH': u'PHILIPPINES',
    'PN': u'PITCAIRN',
    'PL': u'POLAND',
    'PT': u'PORTUGAL',
    'PR': u'PUERTO RICO',
    'QA': u'QATAR',
    'RE': u'R\xc9UNION',
    'RO': u'ROMANIA',
    'RU': u'RUSSIAN FEDERATION',
    'RW': u'RWANDA',
    'BL': u'SAINT BARTH\xc9LEMY',
    'SH': u'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
    'KN': u'SAINT KITTS AND NEVIS',
    'LC': u'SAINT LUCIA',
    'MF': u'SAINT MARTIN (FRENCH PART)',
    'PM': u'SAINT PIERRE AND MIQUELON',
    'VC': u'SAINT VINCENT AND THE GRENADINES',
    'WS': u'SAMOA',
    'SM': u'SAN MARINO',
    'ST': u'SAO TOME AND PRINCIPE',
    'SA': u'SAUDI ARABIA',
    'SN': u'SENEGAL',
    'RS': u'SERBIA',
    'SC': u'SEYCHELLES',
    'SL': u'SIERRA LEONE',
    'SG': u'SINGAPORE',
    'SX': u'SINT MAARTEN (DUTCH PART)',
    'SK': u'SLOVAKIA',
    'SI': u'SLOVENIA',
    'SB': u'SOLOMON ISLANDS',
    'SO': u'SOMALIA',
    'ZA': u'SOUTH AFRICA',
    'GS': u'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
    'SS': u'SOUTH SUDAN',
    'ES': u'SPAIN',
    'LK': u'SRI LANKA',
    'SD': u'SUDAN',
    'SR': u'SURINAME',
    'SJ': u'SVALBARD AND JAN MAYEN',
    'SZ': u'SWAZILAND',
    'SE': u'SWEDEN',
    'CH': u'SWITZERLAND',
    'SY': u'SYRIAN ARAB REPUBLIC',
    'TW': u'TAIWAN, PROVINCE OF CHINA',
    'TJ': u'TAJIKISTAN',
    'TZ': u'TANZANIA, UNITED REPUBLIC OF',
    'TH': u'THAILAND',
    'TL': u'TIMOR-LESTE',
    'TG': u'TOGO',
    'TK': u'TOKELAU',
    'TO': u'TONGA',
    'TT': u'TRINIDAD AND TOBAGO',
    'TN': u'TUNISIA',
    'TR': u'TURKEY',
    'TM': u'TURKMENISTAN',
    'TC': u'TURKS AND CAICOS ISLANDS',
    'TV': u'TUVALU',
    'UG': u'UGANDA',
    'UA': u'UKRAINE',
    'AE': u'UNITED ARAB EMIRATES',
    'GB': u'UNITED KINGDOM',
    'US': u'UNITED STATES',
    'UM': u'UNITED STATES MINOR OUTLYING ISLANDS',
    'UY': u'URUGUAY',
    'UZ': u'UZBEKISTAN',
    'VU': u'VANUATU',
    'VE': u'VENEZUELA, BOLIVARIAN REPUBLIC OF',
    'VN': u'VIET NAM',
    'VG': u'VIRGIN ISLANDS, BRITISH',
    'VI': u'VIRGIN ISLANDS, U.S.',
    'WF': u'WALLIS AND FUTUNA',
    'EH': u'WESTERN SAHARA',
    'YE': u'YEMEN',
    'ZM': u'ZAMBIA',
    'ZW': u'ZIMBABWE',
}


COUNTRIES_PLUS_SIMPLE = (
    (_(u'Afghanistan'), _(u'Afghanistan')),
    (_(u'\xc5land Islands'), _(u'\xc5land Islands')),
    (_(u'Albania'), _(u'Albania')),
    (_(u'Algeria'), _(u'Algeria')),
    (_(u'American Samoa'), _(u'American Samoa')),
    (_(u'Andorra'), _(u'Andorra')),
    (_(u'Angola'), _(u'Angola')),
    (_(u'Anguilla'), _(u'Anguilla')),
    (_(u'Antarctica'), _(u'Antarctica')),
    (_(u'Antigua and Barbuda'), _(u'Antigua and Barbuda')),
    (_(u'Argentina'), _(u'Argentina')),
    (_(u'Armenia'), _(u'Armenia')),
    (_(u'Aruba'), _(u'Aruba')),
    (_(u'Ascension and Tristan Da Cunha Saint Helena'), _(u'Ascension and Tristan Da Cunha Saint Helena')),
    (_(u'Australia'), _(u'Australia')),
    (_(u'Austria'), _(u'Austria')),
    (_(u'Azerbaijan'), _(u'Azerbaijan')),
    (_(u'Bahamas'), _(u'Bahamas')),
    (_(u'Bahrain'), _(u'Bahrain')),
    (_(u'Bangladesh'), _(u'Bangladesh')),
    (_(u'Barbados'), _(u'Barbados')),
    (_(u'Belarus'), _(u'Belarus')),
    (_(u'Belgium'), _(u'Belgium')),
    (_(u'Belize'), _(u'Belize')),
    (_(u'Benin'), _(u'Benin')),
    (_(u'Bermuda'), _(u'Bermuda')),
    (_(u'Bhutan'), _(u'Bhutan')),
    (_(u'Bolivarian Republic of Venezuela'), _(u'Bolivarian Republic of Venezuela')),
    (_(u'Bolivia, Plurinational State of'), _(u'Bolivia, Plurinational State of')),
    (_(u'Bonaire, Sint Eustatius and Saba'), _(u'Bonaire, Sint Eustatius and Saba')),
    (_(u'Bosnia and Herzegovina'), _(u'Bosnia and Herzegovina')),
    (_(u'Botswana'), _(u'Botswana')),
    (_(u'Bouvet Island'), _(u'Bouvet Island')),
    (_(u'Brazil'), _(u'Brazil')),
    (_(u'British Indian Ocean Territory'), _(u'British Indian Ocean Territory')),
    (_(u'British Virgin Islands'), _(u'British Virgin Islands')),
    (_(u'Brunei Darussalam'), _(u'Brunei Darussalam')),
    (_(u'Bulgaria'), _(u'Bulgaria')),
    (_(u'Burkina Faso'), _(u'Burkina Faso')),
    (_(u'Burundi'), _(u'Burundi')),
    (_(u'Cambodia'), _(u'Cambodia')),
    (_(u'Cameroon'), _(u'Cameroon')),
    (_(u'Canada'), _(u'Canada')),
    (_(u'Cape Verde'), _(u'Cape Verde')),
    (_(u'Cayman Islands'), _(u'Cayman Islands')),
    (_(u'Central African Republic'), _(u'Central African Republic')),
    (_(u'Chad'), _(u'Chad')),
    (_(u'Chile'), _(u'Chile')),
    (_(u'China'), _(u'China')),
    (_(u'Christmas Island'), _(u'Christmas Island')),
    (_(u'Cocos (Keeling) Islands'), _(u'Cocos (Keeling) Islands')),
    (_(u'Colombia'), _(u'Colombia')),
    (_(u'Comoros'), _(u'Comoros')),
    (_(u'Congo'), _(u'Congo')),
    (_(u'Congo, The Democratic Republic of the'), _(u'Congo, The Democratic Republic of the')),
    (_(u'Cook Islands'), _(u'Cook Islands')),
    (_(u'Costa Rica'), _(u'Costa Rica')),
    (_(u"C\xf4te D'ivoire"), _(u"C\xf4te D'ivoire")),
    (_(u'Croatia'), _(u'Croatia')),
    (_(u'Cuba'), _(u'Cuba')),
    (_(u'Cura\xe7ao'), _(u'Cura\xe7ao')),
    (_(u'Cyprus'), _(u'Cyprus')),
    (_(u'Czech Republic'), _(u'Czech Republic')),
    (_(u"Democratic People's Republic of Korea"), _(u"Democratic People's Republic of Korea")),
    (_(u'Denmark'), _(u'Denmark')),
    (_(u'Djibouti'), _(u'Djibouti')),
    (_(u'Dominica'), _(u'Dominica')),
    (_(u'Dominican Republic'), _(u'Dominican Republic')),
    (_(u'Ecuador'), _(u'Ecuador')),
    (_(u'Egypt'), _(u'Egypt')),
    (_(u'El Salvador'), _(u'El Salvador')),
    (_(u'Equatorial Guinea'), _(u'Equatorial Guinea')),
    (_(u'Eritrea'), _(u'Eritrea')),
    (_(u'Estonia'), _(u'Estonia')),
    (_(u'Ethiopia'), _(u'Ethiopia')),
    (_(u'Falkland Islands (Malvinas)'), _(u'Falkland Islands (Malvinas)')),
    (_(u'Faroe Islands'), _(u'Faroe Islands')),
    (_(u'Federated States of Micronesia'), _(u'Federated States of Micronesia')),
    (_(u'Fiji'), _(u'Fiji')),
    (_(u'Finland'), _(u'Finland')),
    (_(u'France'), _(u'France')),
    (_(u'French Guiana'), _(u'French Guiana')),
    (_(u'French Polynesia'), _(u'French Polynesia')),
    (_(u'French Southern Territories'), _(u'French Southern Territories')),
    (_(u'Gabon'), _(u'Gabon')),
    (_(u'Gambia'), _(u'Gambia')),
    (_(u'Georgia'), _(u'Georgia')),
    (_(u'Germany'), _(u'Germany')),
    (_(u'Ghana'), _(u'Ghana')),
    (_(u'Gibraltar'), _(u'Gibraltar')),
    (_(u'Greece'), _(u'Greece')),
    (_(u'Greenland'), _(u'Greenland')),
    (_(u'Grenada'), _(u'Grenada')),
    (_(u'Guadeloupe'), _(u'Guadeloupe')),
    (_(u'Guam'), _(u'Guam')),
    (_(u'Guatemala'), _(u'Guatemala')),
    (_(u'Guernsey'), _(u'Guernsey')),
    (_(u'Guinea'), _(u'Guinea')),
    (_(u'Guinea-bissau'), _(u'Guinea-bissau')),
    (_(u'Guyana'), _(u'Guyana')),
    (_(u'Haiti'), _(u'Haiti')),
    (_(u'Heard Island and McDonald Islands'), _(u'Heard Island and McDonald Islands')),
    (_(u'Holy See (Vatican City State)'), _(u'Holy See (Vatican City State)')),
    (_(u'Honduras'), _(u'Honduras')),
    (_(u'Hong Kong'), _(u'Hong Kong')),
    (_(u'Hungary'), _(u'Hungary')),
    (_(u'Iceland'), _(u'Iceland')),
    (_(u'India'), _(u'India')),
    (_(u'Indonesia'), _(u'Indonesia')),
    (_(u'Iran, Islamic Republic of'), _(u'Iran, Islamic Republic of')),
    (_(u'Iraq'), _(u'Iraq')),
    (_(u'Ireland'), _(u'Ireland')),
    (_(u'Islamic Republic of Iran'), _(u'Islamic Republic of Iran')),
    (_(u'Isle of Man'), _(u'Isle of Man')),
    (_(u'Israel'), _(u'Israel')),
    (_(u'Italy'), _(u'Italy')),
    (_(u'Jamaica'), _(u'Jamaica')),
    (_(u'Japan'), _(u'Japan')),
    (_(u'Jersey'), _(u'Jersey')),
    (_(u'Jordan'), _(u'Jordan')),
    (_(u'Kazakhstan'), _(u'Kazakhstan')),
    (_(u'Kenya'), _(u'Kenya')),
    (_(u'Kiribati'), _(u'Kiribati')),
    (_(u"Korea, Democratic People's Republic of"), _(u"Korea, Democratic People's Republic of")),
    (_(u'Korea, Republic of'), _(u'Korea, Republic of')),
    (_(u'Kuwait'), _(u'Kuwait')),
    (_(u'Kyrgyzstan'), _(u'Kyrgyzstan')),
    (_(u"Lao People's Democratic Republic"), _(u"Lao People's Democratic Republic")),
    (_(u'Latvia'), _(u'Latvia')),
    (_(u'Lebanon'), _(u'Lebanon')),
    (_(u'Lesotho'), _(u'Lesotho')),
    (_(u'Liberia'), _(u'Liberia')),
    (_(u'Libya'), _(u'Libya')),
    (_(u'Liechtenstein'), _(u'Liechtenstein')),
    (_(u'Lithuania'), _(u'Lithuania')),
    (_(u'Luxembourg'), _(u'Luxembourg')),
    (_(u'Macao'), _(u'Macao')),
    (_(u'Macedonia, The Former Yugoslav Republic of'), _(u'Macedonia, The Former Yugoslav Republic of')),
    (_(u'Madagascar'), _(u'Madagascar')),
    (_(u'Malawi'), _(u'Malawi')),
    (_(u'Malaysia'), _(u'Malaysia')),
    (_(u'Maldives'), _(u'Maldives')),
    (_(u'Mali'), _(u'Mali')),
    (_(u'Malta'), _(u'Malta')),
    (_(u'Marshall Islands'), _(u'Marshall Islands')),
    (_(u'Martinique'), _(u'Martinique')),
    (_(u'Mauritania'), _(u'Mauritania')),
    (_(u'Mauritius'), _(u'Mauritius')),
    (_(u'Mayotte'), _(u'Mayotte')),
    (_(u'Mexico'), _(u'Mexico')),
    (_(u'Micronesia, Federated States of'), _(u'Micronesia, Federated States of')),
    (_(u'Moldova, Republic of'), _(u'Moldova, Republic of')),
    (_(u'Monaco'), _(u'Monaco')),
    (_(u'Mongolia'), _(u'Mongolia')),
    (_(u'Montenegro'), _(u'Montenegro')),
    (_(u'Montserrat'), _(u'Montserrat')),
    (_(u'Morocco'), _(u'Morocco')),
    (_(u'Mozambique'), _(u'Mozambique')),
    (_(u'Myanmar'), _(u'Myanmar')),
    (_(u'Namibia'), _(u'Namibia')),
    (_(u'Nauru'), _(u'Nauru')),
    (_(u'Nepal'), _(u'Nepal')),
    (_(u'Netherlands'), _(u'Netherlands')),
    (_(u'New Caledonia'), _(u'New Caledonia')),
    (_(u'New Zealand'), _(u'New Zealand')),
    (_(u'Nicaragua'), _(u'Nicaragua')),
    (_(u'Niger'), _(u'Niger')),
    (_(u'Nigeria'), _(u'Nigeria')),
    (_(u'Niue'), _(u'Niue')),
    (_(u'Norfolk Island'), _(u'Norfolk Island')),
    (_(u'Northern Mariana Islands'), _(u'Northern Mariana Islands')),
    (_(u'Norway'), _(u'Norway')),
    (_(u'Occupied Palestinian Territory'), _(u'Occupied Palestinian Territory')),
    (_(u'Oman'), _(u'Oman')),
    (_(u'Pakistan'), _(u'Pakistan')),
    (_(u'Palau'), _(u'Palau')),
    (_(u'Palestinian Territory, Occupied'), _(u'Palestinian Territory, Occupied')),
    (_(u'Panama'), _(u'Panama')),
    (_(u'Papua New Guinea'), _(u'Papua New Guinea')),
    (_(u'Paraguay'), _(u'Paraguay')),
    (_(u'Peru'), _(u'Peru')),
    (_(u'Philippines'), _(u'Philippines')),
    (_(u'Pitcairn'), _(u'Pitcairn')),
    (_(u'Plurinational State of Bolivia'), _(u'Plurinational State of Bolivia')),
    (_(u'Poland'), _(u'Poland')),
    (_(u'Portugal'), _(u'Portugal')),
    (_(u'Province of China Taiwan'), _(u'Province of China Taiwan')),
    (_(u'Puerto Rico'), _(u'Puerto Rico')),
    (_(u'Qatar'), _(u'Qatar')),
    (_(u'Republic of Korea'), _(u'Republic of Korea')),
    (_(u'Republic of Moldova'), _(u'Republic of Moldova')),
    (_(u'R\xe9union'), _(u'R\xe9union')),
    (_(u'Romania'), _(u'Romania')),
    (_(u'Russian Federation'), _(u'Russian Federation')),
    (_(u'Rwanda'), _(u'Rwanda')),
    (_(u'Saint Barth\xe9lemy'), _(u'Saint Barth\xe9lemy')),
    (_(u'Saint Helena, Ascension and Tristan Da Cunha'), _(u'Saint Helena, Ascension and Tristan Da Cunha')),
    (_(u'Saint Kitts and Nevis'), _(u'Saint Kitts and Nevis')),
    (_(u'Saint Lucia'), _(u'Saint Lucia')),
    (_(u'Saint Martin (French Part)'), _(u'Saint Martin (French Part)')),
    (_(u'Saint Pierre and Miquelon'), _(u'Saint Pierre and Miquelon')),
    (_(u'Saint Vincent and the Grenadines'), _(u'Saint Vincent and the Grenadines')),
    (_(u'Samoa'), _(u'Samoa')),
    (_(u'San Marino'), _(u'San Marino')),
    (_(u'Sao Tome and Principe'), _(u'Sao Tome and Principe')),
    (_(u'Saudi Arabia'), _(u'Saudi Arabia')),
    (_(u'Senegal'), _(u'Senegal')),
    (_(u'Serbia'), _(u'Serbia')),
    (_(u'Seychelles'), _(u'Seychelles')),
    (_(u'Sierra Leone'), _(u'Sierra Leone')),
    (_(u'Singapore'), _(u'Singapore')),
    (_(u'Sint Eustatius and Saba Bonaire'), _(u'Sint Eustatius and Saba Bonaire')),
    (_(u'Sint Maarten (Dutch Part)'), _(u'Sint Maarten (Dutch Part)')),
    (_(u'Slovakia'), _(u'Slovakia')),
    (_(u'Slovenia'), _(u'Slovenia')),
    (_(u'Solomon Islands'), _(u'Solomon Islands')),
    (_(u'Somalia'), _(u'Somalia')),
    (_(u'South Africa'), _(u'South Africa')),
    (_(u'South Georgia and the South Sandwich Islands'), _(u'South Georgia and the South Sandwich Islands')),
    (_(u'South Sudan'), _(u'South Sudan')),
    (_(u'Spain'), _(u'Spain')),
    (_(u'Sri Lanka'), _(u'Sri Lanka')),
    (_(u'Sudan'), _(u'Sudan')),
    (_(u'Suriname'), _(u'Suriname')),
    (_(u'Svalbard and Jan Mayen'), _(u'Svalbard and Jan Mayen')),
    (_(u'Swaziland'), _(u'Swaziland')),
    (_(u'Sweden'), _(u'Sweden')),
    (_(u'Switzerland'), _(u'Switzerland')),
    (_(u'Syrian Arab Republic'), _(u'Syrian Arab Republic')),
    (_(u'Taiwan, Province of China'), _(u'Taiwan, Province of China')),
    (_(u'Tajikistan'), _(u'Tajikistan')),
    (_(u'Tanzania, United Republic of'), _(u'Tanzania, United Republic of')),
    (_(u'Thailand'), _(u'Thailand')),
    (_(u'The Democratic Republic of the Congo'), _(u'The Democratic Republic of the Congo')),
    (_(u'The Former Yugoslav Republic of Macedonia'), _(u'The Former Yugoslav Republic of Macedonia')),
    (_(u'Timor-leste'), _(u'Timor-leste')),
    (_(u'Togo'), _(u'Togo')),
    (_(u'Tokelau'), _(u'Tokelau')),
    (_(u'Tonga'), _(u'Tonga')),
    (_(u'Trinidad and Tobago'), _(u'Trinidad and Tobago')),
    (_(u'Tunisia'), _(u'Tunisia')),
    (_(u'Turkey'), _(u'Turkey')),
    (_(u'Turkmenistan'), _(u'Turkmenistan')),
    (_(u'Turks and Caicos Islands'), _(u'Turks and Caicos Islands')),
    (_(u'Tuvalu'), _(u'Tuvalu')),
    (_(u'U.S. Virgin Islands'), _(u'U.S. Virgin Islands')),
    (_(u'Uganda'), _(u'Uganda')),
    (_(u'Ukraine'), _(u'Ukraine')),
    (_(u'United Arab Emirates'), _(u'United Arab Emirates')),
    (_(u'United Kingdom'), _(u'United Kingdom')),
    (_(u'United Republic of Tanzania'), _(u'United Republic of Tanzania')),
    (_(u'United States'), _(u'United States')),
    (_(u'United States Minor Outlying Islands'), _(u'United States Minor Outlying Islands')),
    (_(u'Uruguay'), _(u'Uruguay')),
    (_(u'Uzbekistan'), _(u'Uzbekistan')),
    (_(u'Vanuatu'), _(u'Vanuatu')),
    (_(u'Venezuela, Bolivarian Republic of'), _(u'Venezuela, Bolivarian Republic of')),
    (_(u'Viet Nam'), _(u'Viet Nam')),
    (_(u'Virgin Islands, British'), _(u'Virgin Islands, British')),
    (_(u'Virgin Islands, U.S.'), _(u'Virgin Islands, U.S.')),
    (_(u'Wallis and Futuna'), _(u'Wallis and Futuna')),
    (_(u'Western Sahara'), _(u'Western Sahara')),
    (_(u'Yemen'), _(u'Yemen')),
    (_(u'Zambia'), _(u'Zambia')),
    (_(u'Zimbabwe'), _(u'Zimbabwe')),
)